### ISSUE TITLE
Regression: Nested signed mail showed as nameless.eml

### ISSUE THREAD

**Issue by minimalisticMe** [Sicos1977/MSGReader#397] opened 2024-03-10 10:53 UTC
**Describe the bug**
When extracting a mail with multiple nested mails (mail attachments) I can extract all mails correctly, but one mail is named incorrectly.
One of the attached mails is a singed mail and the name of this mail is "Nameless.eml" instead of the correct name.
This was working correctly on a prior version (I am not sure which one, it was some time mid last year).

**Platform (please complete the following information):**
 - OS: Windows 11
 - .NET Framework: .NET 8
 - MsgReader Version: 5.5.5

**Exception**
No exception, just incorrect parsing.

**To Reproduce**
Is there a way to share the mail securely? It contains personal data of me.

**Expected behavior**
The name of the attached signed mail is read correctly.

**Code Snippets**
```csharp
var eml = MsgReader.Mime.Message.Load(stream);
foreach (var item in eml.Attachments)
{
     if (item.IsAttachment)
     {
         var originalFilename = item.FileName; // wrong in one of the attachments
     }
}
```

**Comment by minimalisticMe** [comment] 2024-03-31 17:22
Can I help by sending you the eml-file in question?

**Comment by Sicos1977** [comment] 2024-04-02 03:54
Yes please sent it to ***@***.*** ... Zip the file before sendingMet vriendelijke groet,Kees van Spelde

**Comment by minimalisticMe** [comment] 2024-04-02 07:36
@Sicos1977 Thank you very much for looking into this. I sent you a mail to ***@hotmail.com (found in another issue, as this mail-address was redacted).

**Comment by Sicos1977** [comment] 2024-04-06 09:54
Please try the latest source to see if the problem is fixed with this commit --> b6c26efc124fb43bfec8593efff0dd5db70800de

**Closed** 2024-04-06 09:55 UTC
Labels: bug, enhancement

**Comment by Sicos1977** [comment] 2024-04-06 13:12
https://www.nuget.org/packages/MsgReader/5.5.6

**Comment by minimalisticMe** [comment] 2024-04-07 10:15
@Sicos1977 I can confirm: After updating to nuget package now everything works as expected. 
Thank you very much.
